# Generated by Django 5.1.7 on 2025-05-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectCode', models.CharField(max_length=100)),
                ('SubjectName', models.CharField(max_length=255)),
                ('Branch', models.CharField(max_length=200)),
                ('Semester', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='pdfs/quantum/btech')),
            ],
        ),
        migrations.CreateModel(
            name='MCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectCode', models.CharField(max_length=100)),
                ('SubjectName', models.CharField(max_length=255)),
                ('Branch', models.CharField(max_length=200)),
                ('Semester', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='pdfs/quantum/btech')),
            ],
        ),
        migrations.AlterField(
            model_name='btech',
            name='pdf',
            field=models.FileField(upload_to='pdfs/quantum/btech'),
        ),
    ]
