# Generated by Django 5.1.7 on 2025-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0002_mba_mca_alter_btech_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mba',
            name='pdf',
            field=models.FileField(upload_to='pdfs/quantum/mba'),
        ),
        migrations.AlterField(
            model_name='mca',
            name='pdf',
            field=models.FileField(upload_to='pdfs/quantum/mca'),
        ),
    ]
