# Generated by Django 5.1.7 on 2025-05-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0003_alter_mba_pdf_alter_mca_pdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BTech',
            new_name='BTechQuantum',
        ),
        migrations.RenameModel(
            old_name='MBA',
            new_name='MBAQuantum',
        ),
        migrations.RenameModel(
            old_name='MCA',
            new_name='MCAQuantum',
        ),
    ]
