# Generated by Django 5.1.7 on 2025-05-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0004_rename_btech_btechquantum_rename_mba_mbaquantum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btechquantum',
            name='provider',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbaquantum',
            name='provider',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcaquantum',
            name='provider',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
