# Generated by Django 5.1.7 on 2025-05-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BTech',
            new_name='BTechExamPapers',
        ),
        migrations.RenameModel(
            old_name='MBA',
            new_name='MBAExamPapers',
        ),
        migrations.RenameModel(
            old_name='MCA',
            new_name='MCAExamPapers',
        ),
    ]
