# Generated by Django 5.1.7 on 2025-05-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0002_rename_btech_btechexampapers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btechexampapers',
            name='provider',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbaexampapers',
            name='provider',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcaexampapers',
            name='provider',
            field=models.CharField(default='known', max_length=255),
            preserve_default=False,
        ),
    ]
