# Generated by Django 5.1.7 on 2025-05-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btech',
            name='pdf',
            field=models.FileField(upload_to='pdfs/notes/btech'),
        ),
        migrations.AlterField(
            model_name='mba',
            name='pdf',
            field=models.FileField(upload_to='pdfs/notes/mba'),
        ),
        migrations.AlterField(
            model_name='mca',
            name='pdf',
            field=models.FileField(upload_to='pdfs/notes/mca'),
        ),
    ]
