# Generated by Django 5.1.7 on 2025-05-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_btech_pdf_alter_mba_pdf_alter_mca_pdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BTech',
            new_name='BTechNotes',
        ),
        migrations.RenameModel(
            old_name='MBA',
            new_name='MBANotes',
        ),
        migrations.RenameModel(
            old_name='MCA',
            new_name='MCANotes',
        ),
    ]
