# Generated by Django 5.1.7 on 2025-05-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_btech_btechnotes_rename_mba_mbanotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btechnotes',
            name='provider',
            field=models.CharField(default='known', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbanotes',
            name='provider',
            field=models.CharField(default='known', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcanotes',
            name='provider',
            field=models.CharField(default='known', max_length=255),
            preserve_default=False,
        ),
    ]
